CC = gcc
CFLAGS =
TARGET = tp2virtual 
OBJ_SRC = objetos
SOURCES_C = $(shell find . -name '*.c')
OBJ = $(patsubst ./%, $(OBJ_SRC)/%, $(SOURCES_C:.c=.o))

$(OBJ_SRC)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

build: $(OBJ)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJ)

run: $(TARGET)
	./$(TARGET) teste.txt


clean:
	rm -rf $(OBJ_SRC)
