CC = gcc
CFLAGS =
TARGET = tp2virtual 
OBJ_SRC = objetos
SOURCES_C = $(shell find . -name '*.c')
OBJ = $(patsubst ./%, $(OBJ_SRC)/%, $(SOURCES_C:.c=.o))
LIBFLAG = -lm

$(OBJ_SRC)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

build: $(OBJ)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJ) $(LIBFLAG)

run: $(TARGET)
	./$(TARGET) lru compiler_test.log 1024 16384 

clean:
	rm -rf $(OBJ_SRC)
